# Generated by Django 3.2.9 on 2022-01-31 18:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.FileField(db_index=True, upload_to='not_used')),
                ('frame_ammount', models.IntegerField(default=-1)),
                ('fps', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='VideoOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneConfigDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.video')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('poly', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('zone_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.zoneconfigdb')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.videoowner'),
        ),
        migrations.CreateModel(
            name='DetectionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('last_bbox', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
                ('first_bbox', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
                ('input_zone', models.CharField(max_length=64)),
                ('output_zone', models.CharField(max_length=64)),
                ('dist_btw_bbox', models.IntegerField(default=-1)),
                ('frames_counter', models.IntegerField(default=0)),
                ('last_frame_detection_id', models.IntegerField(default=0)),
                ('detection_time', models.TimeField(auto_now=True)),
                ('last_detection_time', models.TimeField(null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.video')),
            ],
        ),
        migrations.CreateModel(
            name='AfarmentDataDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('maneuver', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=64)),
                ('class_id', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.video')),
            ],
        ),
    ]
