# Generated by Django 3.2.9 on 2022-01-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Proccesing', 'Proccesing'), ('Finished', 'Finished')], default='Queued', max_length=64),
        ),
    ]
