# Generated by Django 3.2.13 on 2022-05-03 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220202_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='afarmentdatadb',
            name='input_zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_zone', to='manager.zone'),
        ),
        migrations.AddField(
            model_name='afarmentdatadb',
            name='output_zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_zone', to='manager.zone'),
        ),
    ]
