# Generated by Django 3.2.13 on 2022-05-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20220502_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='zone_config',
        ),
        migrations.AddField(
            model_name='zone',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.video'),
        ),
        migrations.DeleteModel(
            name='ZoneConfigDB',
        ),
    ]
